'use client'
import React, { useState } from 'react';
import Footer from '@/components/footer/footer';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import Nav from '@/components/nav/nav'; // Import Nav component

import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 
  

  return (
    <html lang="en">
      <body className={`${inter.className} bg-dark`}>
        <Nav  />
        {children}
        <Footer />
      </body>
    </html>
  );
}
